CREATE TABLE `feeds` (
  `feedID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `postType` ENUM('video', 'link', 'wiki', 'blog') NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `source` VARCHAR(45),
  `gameTitleID` INTEGER UNSIGNED,
  `parameters` VARCHAR(255),
  `entryPath` VARCHAR(255),
  `gameTitlePath` VARCHAR(255),
  `identifierPath` VARCHAR(255),
  `postTitlePath` VARCHAR(255),
  `urlPath` VARCHAR(255),
  `imagePath` VARCHAR(255),
  `descriptionPath` VARCHAR(255),
  `contentPath` VARCHAR(255),
  `require` VARCHAR(255),
  `reject` VARCHAR(255),
  `replace` VARCHAR(255),
  `status` ENUM('active','inactive') NOT NULL,
  `interval` ENUM('daily','weekly','bi weekly','monthly','bi monthly','6 months') NOT NULL,
  `priority` TINYINT(3) UNSIGNED NOT NULL,
  `poster` varchar(10) NOT NULL,
  `posterID` int(10) unsigned NOT NULL,
  `dateAdded` DATETIME NOT NULL,
  `lastModified` DATETIME NOT NULL,
  PRIMARY KEY (`feedID`),
  INDEX `status_interval_priority`(`status`, `interval`, `priority`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `feedsHistory` (
  `feedsHistoryID` int(10) unsigned NOT NULL auto_increment,
  `recordEditor` varchar(10) NOT NULL,
  `recordEditorID` int(10) unsigned NOT NULL,
  `action` varchar(10) NOT NULL,
  `comments` text NOT NULL,
  `feedID` INTEGER UNSIGNED NOT NULL,
  `postType` ENUM('video', 'link', 'wiki', 'blog') NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `source` VARCHAR(45),
  `gameTitleID` INTEGER UNSIGNED,
  `parameters` VARCHAR(255),
  `entryPath` VARCHAR(255),
  `gameTitlePath` VARCHAR(255),
  `identifierPath` VARCHAR(255),
  `postTitlePath` VARCHAR(255),
  `urlPath` VARCHAR(255),
  `imagePath` VARCHAR(255),
  `descriptionPath` VARCHAR(255),
  `contentPath` VARCHAR(255),
  `require` VARCHAR(255),
  `reject` VARCHAR(255),
  `replace` VARCHAR(255),
  `status` ENUM('active','inactive') NOT NULL,
  `interval` ENUM('daily','weekly','bi weekly','monthly','bi monthly','6 months') NOT NULL,
  `priority` TINYINT(3) UNSIGNED NOT NULL,
  `poster` varchar(10) NOT NULL,
  `posterID` int(10) unsigned NOT NULL,
  `dateAdded` DATETIME NOT NULL,
  `lastModified` DATETIME NOT NULL,
  `effectiveThrough` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY (`feedsHistoryID`),
  KEY (`feedID`),
  KEY `lastModified_effectiveThrough` (`lastModified`,`effectiveThrough`)
)
ENGINE = InnoDB DEFAULT CHARSET=utf8;
